app:
  redis:
    topic:
      like-achievement: like_achievement_topic
  achievements:
    allLove:
      name: "ALL LOVE"
      requiredLikes: 1000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: achievement-service
      auto-offset-reset: earliest
      topics:
        post:
          name: post-topic
          num-partitions: 1
          replication-factor: 1

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

achievements:
  sensei-name: "Sensei"

redis:
  channel-topic: mentorship_channel
