spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  kafka:
      bootstrap-servers: localhost:9092
      topics:
        achievement: user_achievement  # Название топика
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

achievement:
  titles:
    handsome: "Handsome Achievement"

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel
        profile_pic: profile_pic_channel

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: achievement_
      cache-null-values: false

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: achievement-async-

server:
  port: 8085

logging:
  level:
    root: info
    org.springframework.cache: debug

project-service:
  host: localhost
  port: 8082

kafka:
  host: "localhost:9092"
  topics:
    recommendation: recommendation
  group: recommendation-service
  concurrency: 3
  properties:
    security.protocol: SSL
    ssl.truststore.location: /path/to/truststore.jks
    ssl.truststore.password: password

achievements:
  nice-guy:
    title: Nice guy
    required-progress: 10