spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      topic:
        likeChannel: like_channel
      channel:
        achievement: achievement_channel
        follower: follower_channel
        mentorship: mentorship_channel
        album: album_channel
        profile-picture: profile_pic_channel
        post: post_channel
        comment_achievement: comment_channel
      cache:
        achievement-key: achievements

cache:
  achievement:
    update-schedule: '0 */1 * * * *' # every minute

achievement-handler:
  all-love-achievement-handler:
    achievement-name: ALL LOVE
    achievement-required-likes: 1000
  handsome-achievement-handler:
    achievement-name: HANDSOME
    points: 1
  librarian-achievement-handler:
    achievement-name: LIBRARIAN
    points:
  writer-achievement-handler:
    achievement-name: WRITER
    points: 100
  sensei-achievement-handler:
    achievement-name: SENSEI
    points: 30
  comment-achievement-handler:
    achievement-name: EXPERT
    points: 5

server:
  port: 8085

executors:
  thread-pool-size: 10

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

handler:
  achievement:
    sensei:
