spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel
        post: post_channel
#        comment_achievement: comment_channel

cache:
  achievement:
#    achievement-key: achievements
    update-schedule: '0 */1 * * * *' # every minute


server:
  port: 8085

executors:
  thread-pool-size: 10

achievements:
  writer: WRITER

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
