spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel
        comment_achievement: post_comment_channel
        profile_pic_channel: profile_pic_channel
    cache:
      title:
        expert: EXPERT
achievements:
  handsome: HANDSOME


server:
  port: 8085

logging:
  level:
    root: info
    faang.school.achievement: debug

project-service:
  host: localhost
  port: 8082

user-service:
  host: localhost
  port: 8080