spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        comment_channel:
          name: comment_channel
        follower_channel:
          name: follower_channel
        like_channel:
          name: like_channel
        mentorship_channel:
          name: mentorship_channel
        project_channel:
          name: project_channel

server:
  port: 8085

logging:
  level:
    root: info

achievements:
  title:
    love_everyone: love_everyone
    sensei: SENSEI
    businessman: BUSINESSMEN
    expert: EXPERT
    blogger: BLOGGER