spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      topic:
        likeChannel: like_channel
      channel:
        achievement: achievement_channel
        follower: follower_channel
        album: album_channel
        profile-picture:  profile_pic_channel
        post: post_channel
      cache:
        achievement-key: achievements

cache:
  achievement:
    update-schedule: '0 */1 * * * *' # every minute

achievement-handler:
  all-love-achievement-handler:
    achievement-name: ALL LOVE
    achievement-required-likes: 1000
  handsome-achievement-handler:
    achievement-name: HANDSOME
  librarian-achievement-handler:
    achievement-name: LIBRARIAN
  writer-achievement-handler:
    achievement-name: WRITER

server:
  port: 8085

executors:
  thread-pool-size: 10

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
