spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        achievement: achievement_channel
        follower: follower_channel
        post: post_channel
        mentorship: mentorship_channel

async:
  thread-pool:
    settings:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

achievement-service:
  follower-handler:
    thread-pool:
      corePoolSize: 1
      maximumPoolSize: 10
      keepAliveTime: 0
  achievement:
    followers:
      name: subscribers
    mentorship:
      name: sensei
  mentorship-handler:
    thread-pool:
      corePoolSize: 1
      maximumPoolSize: 10
      keepAliveTime: 0