spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        achievement: achievement_channel
        follower: follower_channel
        recommendation: recommendation_channel
        invite: invitation-channel
        post_achievement: post-achievement-channel
        comment: comment-channel

  config:
    import: classpath:resource_achievement/achievement.yaml

  async_config:
    core_pool_size: 5
    max_pool_size: 10
    queue_capacity: 50
    thread_name_prefix: AsyncTaskThread

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082