spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      achievement-cache-key: achievement-cache-key
      cache-ttl-hours: 24
      channel:
        achievement: achievement_channel
        follower: follower_channel
        post: post_channel

handler:
  executor-pool-parameters:
    core-pool-size: 10
    max-pool-capacity: 20
    queue-capacity: 40
    retry-parameters:
      max-attempts: 5
      backoff-delay: 10
  thread-pool-executor-parameters:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 100
    await-termination-seconds: 60
  achievement:
    names:
      writer: WRITER
        mentorship: mentorship_start_channel

listener:
  type:
    achievements:
      sens


server:
  port: 8095

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

cache:
    achievement:
      update-schedule : "@hourly"
