spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel
        team: team_channel
        comment: comment_channel
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 10000
        keep-alive: 60
        thread-name-prefix: AchievementPool

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

  achievements:
    conglomerate: CONGLOMERATE
    manager: MANAGER
    expert: EXPERT

