spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        follower: follower_channel
        post: post_channel
        profile_pic: profile_pic_channel
        like: like_channel

  kafka:
    host: localhost
    port: 9092
    topics:
      project_topic: project_channel
    consumer:
      group-id: Group1
    concurrency: 3
    poll-timeout: 3000

listener:
  type:
    achievements:
      opinion_leader: OPINION LEADER
      handsome: HANDSOME
      all_love: ALL LOVE
      businessman: BUSINESSMAN

handler:
  executor_pool_parameters:
    core_pool_size: 10
    max_pool_capacity: 20
    queue_capacity: 40
    thread_name_prefix: AchievementHandlerThread-

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
