name: Java Griffon CI pipeline

on:
  push:
    branches:
      - griffon-master
  pull_request:
    branches:
      - griffon-master

jobs:
  build:
    runs-on: ubuntu-latest
  services:
    postgres:
      image: postgres:13.3
      env:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test